"""Amendment C: the conversions and gates Task 9 needs, checked against R where R can check them.

Two kinds of reference:

* `validation/fixtures/r_reference.json`, regenerated by `make_r_fixtures.R` — for
  `combine_groups` it holds a raw sample split in two, so the combined summary MUST reproduce the
  whole sample's mean and SD exactly; for the five-number estimators it holds samples whose true
  mean and SD are known; `leave1out` and `regtest(predictor="sqrtninv")` come straight from metafor.
* published formulas (Luo 2018, Shi 2020, Wan 2014, Cochrane 6.5.2.10 / 16.5.4) for the shapes R
  has no function for.

The gates are not statistics but refusals: a statistic from a design that cannot carry a
between-group contrast must raise, not return a plausible number.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest
from scipy.stats import norm

from canopy.stats import conversions as cv
from canopy.stats import effect_sizes as es
from canopy.stats.effect_sizes import NotConvertible
from canopy.stats.meta import egger_test, funnel_data, leave_one_out

FIX = json.loads((Path(__file__).parent.parent / "validation/fixtures/r_reference.json").read_text())


# --------------------------------------------------------------------------- combining arms
def test_combining_two_arms_reproduces_the_whole_sample():
    """Cochrane 6.5.2.10: the point of the formula is that it is exact, so R's raw sample is the
    reference, not another implementation of the same algebra."""
    r = FIX["combine_raw"]
    mean, sd, n = cv.combine_groups(r["m1"], r["sd1"], r["n1"], r["m2"], r["sd2"], r["n2"])
    assert n == r["n"]
    assert mean == pytest.approx(r["mean"], abs=1e-10)
    assert sd == pytest.approx(r["sd"], abs=1e-10)


def test_a_combined_arm_feeds_escalc_unchanged():
    r = FIX["combine_raw"]
    mean, sd, n = cv.combine_groups(r["m1"], r["sd1"], r["n1"], r["m2"], r["sd2"], r["n2"])
    ctrl = r["control"]
    d = es.cohens_d(mean, sd, n, ctrl["m"], ctrl["sd"], ctrl["n"])
    assert d == pytest.approx(r["escalc_d_yi"], abs=1e-9)
    assert es.var_smd(d, n, ctrl["n"], "borenstein") == pytest.approx(r["escalc_d_vi"], abs=1e-9)


def test_combining_identical_arms_keeps_the_mean_and_widens_the_denominator():
    """Two identical arms have no between-arm spread, so the combined SD is just the two sums of
    squares over N−1 = 39 rather than over the 38 degrees of freedom a pooled SD would use."""
    mean, sd, n = cv.combine_groups(10.0, 2.0, 20, 10.0, 2.0, 20)
    assert (mean, n) == (10.0, 40)
    assert sd == pytest.approx(math.sqrt(2 * 19 * 4 / 39))
    assert sd < 2.0


def test_combining_needs_two_real_groups():
    with pytest.raises(ValueError):
        cv.combine_groups(10.0, 2.0, 1, 10.0, 2.0, 0)


# --------------------------------------------------------------------------- shared controls
def test_a_shared_control_is_split_between_the_comparisons():
    """Cochrane 16.5.4: a control arm used in k comparisons contributes n/k to each."""
    assert cv.split_control(30, 3) == pytest.approx(10.0)
    assert cv.split_control(30, 1) == pytest.approx(30.0)


def test_splitting_a_control_needs_at_least_one_comparison():
    with pytest.raises(ValueError):
        cv.split_control(30, 0)


# --------------------------------------------------------------------------- summary statistics
def test_median_and_quartiles_recover_a_known_mean_and_sd():
    r = FIX["five_number"]
    mean, sd = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    assert mean == pytest.approx(r["mean"], rel=0.01)
    assert sd == pytest.approx(r["sd"], rel=0.05)


def test_the_five_number_summary_beats_the_quartiles_alone():
    r = FIX["five_number"]
    _, sd_iqr = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    mean5, sd5 = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                             r["n"])
    assert mean5 == pytest.approx(r["mean"], rel=0.01)
    assert abs(sd5 - r["sd"]) <= abs(sd_iqr - r["sd"]) + 1e-9


def test_the_estimators_still_work_on_a_small_sample():
    r = FIX["five_number_small"]
    mean, sd = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    assert mean == pytest.approx(r["mean"], rel=0.10)
    assert sd == pytest.approx(r["sd"], rel=0.35)


def test_the_wan_fallback_is_available_and_differs_from_shi():
    r = FIX["five_number"]
    _, shi = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                         r["n"])
    _, wan = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                         r["n"], method="wan")
    assert wan != pytest.approx(shi, abs=1e-12)
    # Wan 2014 eq. 10 is the unweighted average of the two Shi components
    xi = 2 * norm.ppf((r["n"] - 0.375) / (r["n"] + 0.25))
    eta = 2 * norm.ppf((0.75 * r["n"] - 0.125) / (r["n"] + 0.25))
    assert wan == pytest.approx(0.5 * (r["max"] - r["min"]) / xi
                                + 0.5 * (r["q3"] - r["q1"]) / eta, abs=1e-9)


def test_the_quartiles_must_be_ordered():
    with pytest.raises(ValueError):
        cv.mean_sd_from_median_iqr(10.0, 12.0, 8.0, 20)
    with pytest.raises(ValueError):
        cv.mean_sd_from_five_number(5.0, 8.0, 10.0, 9.0, 20.0, 20)


# --------------------------------------------------------------------------- the amendment-C gates
def test_a_two_group_t_converts():
    r = es.smd_from_t(5.25, 12, 12, df=22, design="independent_t", higher_is_better=True)
    assert r.route == "t_stat"
    assert r.d == pytest.approx(es.d_from_t(5.25, 12, 12))
    assert r.details["flags"] == []


@pytest.mark.parametrize("design", ["mixed_main_effect", "interaction", "paired", "ancova",
                                    "welch", "unknown"])
def test_a_design_that_cannot_carry_the_contrast_is_refused(design):
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_t(5.25, 12, 12, df=22, design=design)
    assert design in str(excinfo.value)


def test_degrees_of_freedom_that_do_not_match_the_group_sizes_are_refused():
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_t(5.25, 12, 12, df=40, design="independent_t")
    assert "40" in str(excinfo.value) and "22" in str(excinfo.value)


def test_a_degrees_of_freedom_shortfall_nothing_explains_is_refused():
    """DECISION-v2 C9: "A df tolerance may absorb a shortfall only when the shortfall is
    *explained* … otherwise require exact equality."

    The old +/-2 window admitted `df = 20` at n = 12/12, and `F(1,36)` at n = 20/20 — the shape of
    a two-covariate ANCOVA reported as a one-way. No arithmetic here can tell that apart from the
    two-group test, so the default is refusal.
    """
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_t(5.25, 12, 12, df=20, design="independent_t")
    assert "20" in str(excinfo.value) and "22" in str(excinfo.value)
    with pytest.raises(NotConvertible) as excinfo:        # C9's own acceptance input
        es.smd_from_f(4.2, 20, 20, a_greater=True, df1=1, df2=36, design="independent_t")
    assert "36" in str(excinfo.value) and "38" in str(excinfo.value)


def test_an_explained_shortfall_is_admitted_and_flagged_rather_than_refused():
    """The other half of C9: the paper's own reported participant total explains the gap (a stated
    exclusion that also reduced n), so the conversion runs — flagged, never silently."""
    r = es.smd_from_t(5.25, 12, 12, df=20, design="independent_t",
                      df_shortfall_explained="df_off_by_2")
    assert "df_off_by" in r.details["flags"][0]


def test_missing_degrees_of_freedom_are_allowed_but_flagged():
    r = es.smd_from_t(5.25, 12, 12, design="independent_t")
    assert r.details["flags"] == ["df_missing"]


def test_an_f_with_more_than_one_numerator_degree_of_freedom_is_refused():
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_f(7.58, 12, 12, df1=3, df2=22, design="one_way_between", a_greater=True)
    assert "df1" in str(excinfo.value)


def test_a_one_way_between_f_converts():
    r = es.smd_from_f(7.58, 12, 12, df1=1, df2=22, design="one_way_between", a_greater=True)
    assert r.d == pytest.approx(es.d_from_f(7.58, 12, 12, 1))
    assert r.route == "f_stat"


def test_the_mixed_design_f_that_bock_prints_is_refused():
    """F(1,22)=7.58 for the grouping factor in a mixed ANOVA: right dfs, wrong error term."""
    with pytest.raises(NotConvertible):
        es.smd_from_f(7.58, 12, 12, df1=1, df2=22, design="mixed_main_effect", a_greater=True)


def test_a_p_value_is_gated_the_same_way():
    with pytest.raises(NotConvertible):
        es.smd_from_p(0.03, 12, 12, design="interaction", a_greater=True)
    r = es.smd_from_p(0.03, 12, 12, df=22, design="independent_t", a_greater=True)
    assert r.route == "p_value"


def test_convertibility_explains_itself():
    ok, reason, flags = es.convertibility("independent_t", 22, 12, 12)
    assert ok is True and reason == "" and flags == []
    ok, reason, flags = es.convertibility("paired", 22, 12, 12)
    assert ok is False and "paired" in reason


# --------------------------------------------------------------------------- funnel / Egger / LOO
def test_egger_without_group_sizes_keeps_the_classic_predictor():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    assert result.predictor == "precision" and result.k == late["k"]
    assert result.df == late["k"] - 2


def test_egger_matches_the_rmd_regression():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    ref = late["egger_rmd"]
    assert result.intercept == pytest.approx(ref["intercept"], abs=1e-6)
    assert result.intercept_se == pytest.approx(ref["intercept_se"], abs=1e-6)
    assert result.t == pytest.approx(ref["intercept_t"], abs=1e-6)
    assert result.p == pytest.approx(ref["intercept_p"], abs=1e-6)


def test_the_pustejovsky_rodgers_predictor_matches_metafor_regtest():
    """With group sizes the predictor is √((nA+nB)/(nA·nB)), which does not depend on the effect
    size itself — metafor::regtest(predictor="sqrtninv") with ni = nA·nB/(nA+nB)."""
    ref = FIX["egger_pr"]
    result = egger_test(ref["TE"], ref["seTE"], n_a=ref["n_a"], n_b=ref["n_b"])
    assert result.predictor == "sqrt_inv_n"
    assert result.t == pytest.approx(ref["zval"], abs=1e-8)
    assert result.p == pytest.approx(ref["pval"], abs=1e-8)
    assert result.estimate == pytest.approx(ref["est"], abs=1e-8)
    assert result.estimate_ci_low == pytest.approx(ref["ci.lb"], abs=1e-8)
    assert result.estimate_ci_high == pytest.approx(ref["ci.ub"], abs=1e-8)
    assert result.df == ref["dfs"]


def test_the_asymmetry_coefficient_has_one_unambiguous_name():
    """`intercept` is the asymmetry coefficient in BOTH variants (the fitted intercept for the
    classic predictor, the fitted slope for the sample-size one), so downstream code reads one
    field; the aliases say which is which."""
    ref = FIX["egger_pr"]
    classic = egger_test(FIX["cisneros_late"]["TE"], FIX["cisneros_late"]["seTE"])
    modified = egger_test(ref["TE"], ref["seTE"], n_a=ref["n_a"], n_b=ref["n_b"])
    for result in (classic, modified):
        assert result.bias_coefficient == result.intercept
        assert result.limit_estimate == result.estimate == result.slope
        assert result.t == pytest.approx(result.intercept / result.intercept_se, abs=1e-12)


def test_egger_needs_three_studies():
    """metafor::regtest refuses below k=3, and so must we: two studies leave no residual degrees
    of freedom to test the asymmetry coefficient against."""
    with pytest.raises(ValueError, match="3 studies"):
        egger_test([0.1, 0.2], [0.1, 0.2])


def test_the_classic_egger_also_matches_metafors_lm_variant():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    assert result.t == pytest.approx(FIX["egger_sei_lm"]["zval"], abs=1e-8)
    assert result.p == pytest.approx(FIX["egger_sei_lm"]["pval"], abs=1e-8)


def test_leave_one_out_matches_metafor():
    late = FIX["cisneros_late"]
    ref = FIX["leave_one_out"]
    vi = np.asarray(late["seTE"], float) ** 2
    rows = leave_one_out(late["TE"], vi, method="REML")
    assert len(rows) == ref["k"]
    assert [r.omitted for r in rows] == list(range(ref["k"]))
    np.testing.assert_allclose([r.estimate for r in rows], ref["estimate"], atol=1e-6)
    np.testing.assert_allclose([r.se for r in rows], ref["se"], atol=1e-6)
    np.testing.assert_allclose([r.ci_low for r in rows], ref["ci.lb"], atol=1e-5)
    np.testing.assert_allclose([r.ci_high for r in rows], ref["ci.ub"], atol=1e-5)
    np.testing.assert_allclose([r.tau2 for r in rows], ref["tau2"], atol=1e-5)
    np.testing.assert_allclose([100 * r.I2 for r in rows], ref["I2"], atol=1e-4)


def test_leave_one_out_carries_the_study_labels():
    rows = leave_one_out([0.1, 0.2, 0.3], [0.01, 0.02, 0.03], labels=["a", "b", "c"])
    assert [r.label for r in rows] == ["a", "b", "c"] and rows[0].k == 2


def test_funnel_data_gives_the_points_and_the_pseudo_confidence_contours():
    late = FIX["cisneros_late"]
    vi = np.asarray(late["seTE"], float) ** 2
    data = funnel_data(late["TE"], vi, labels=late["study"])
    assert len(data["yi"]) == len(late["TE"]) and len(data["sei"]) == len(late["TE"])
    assert data["estimate"] == pytest.approx(late["REML"]["TE.random"], abs=1e-6)
    assert data["se_max"] == pytest.approx(max(late["seTE"]))
    for level in (0.95, 0.99):
        contour = data["contours"][str(level)]
        assert contour["se"][0] == 0.0
        assert contour["low"][0] == pytest.approx(data["estimate"])
        assert contour["low"][-1] < data["estimate"] < contour["high"][-1]
    assert data["labels"][0] == late["study"][0]


# --------------------------------------------------------------------------- digitisation variance
def test_finite_differences_reproduce_the_analytic_partial_derivatives():
    """d = (m_a − m_b)/s_p, so ∂d/∂m_a = 1/s_p exactly — the numerical version must agree."""
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)

    def d_of(m_a, sd_a, m_b, sd_b):
        return es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12)

    var, parts = cv.partial_variance(d_of, values, {"m_a": 0.5, "m_b": 0.5})
    sp = es.pooled_sd(11.12, 12, 11.82, 12)
    analytic = (0.5 / sp) ** 2 + (0.5 / sp) ** 2
    assert var == pytest.approx(analytic, rel=1e-6)
    assert parts["m_a"] == pytest.approx((0.5 / sp) ** 2, rel=1e-6)
    assert "sd_a" not in parts


def test_an_input_with_no_uncertainty_contributes_nothing():
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)
    var, parts = cv.partial_variance(
        lambda m_a, sd_a, m_b, sd_b: es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12), values,
        {"m_a": 0.5, "m_b": None, "sd_a": 0.0})
    assert set(parts) == {"m_a"} and var > 0


def test_no_uncertainty_at_all_is_zero_variance():
    var, parts = cv.partial_variance(lambda x: x ** 2, {"x": 3.0}, {})
    assert var == 0.0 and parts == {}


def test_the_dispersion_partials_are_included_when_the_digitizer_measured_them():
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)
    var, parts = cv.partial_variance(
        lambda m_a, sd_a, m_b, sd_b: es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12), values,
        {"m_a": 0.5, "m_b": 0.5, "sd_a": 0.4, "sd_b": 0.4})
    assert set(parts) == {"m_a", "m_b", "sd_a", "sd_b"}
    assert var > math.fsum(parts[k] for k in ("m_a", "m_b")) > 0


# --------------------------------------------------------------------- P-B: what a statistic contrasts
def test_a_test_against_a_constant_is_refused_even_when_its_df_match_the_group_sizes():
    """P-B's code-side counterpart. The prompt tells a model that a test of one group against zero
    is not a `value` source; this is the same rule where it binds.

    Heuer & Hegele print "tests of adaptive shifts against zero" one paragraph away from the
    between-group ANOVA, on the same measure, with degrees of freedom that look right. Nothing but
    the recorded contrast separates them.
    """
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_t(2.1, 20, 20, df=38, design="independent_t", contrast_kind="against_constant",
                      within_factors=[], outcome_averages_over=[])
    assert "constant" in str(exc.value) and "n_a + n_b - 2" in str(exc.value)


def test_a_contrast_nobody_recorded_is_refused_rather_than_assumed_to_be_the_groups():
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_t(2.1, 20, 20, df=38, design="independent_t", contrast_kind="unknown",
                      within_factors=[], outcome_averages_over=[])
    assert "nobody recorded" in str(exc.value)


def test_an_interaction_is_refused_by_its_contrast_as_well_as_by_its_design():
    ok, reason = es.contrast_ok("interaction")
    assert ok is False and "interaction" in reason
    ok, reason = es.contrast_ok("within")
    assert ok is False and "within-subject" in reason


def test_the_case_p_b_exists_to_rescue_still_converts():
    """t(38) = 2.1 from an independent-groups t test, no means printed anywhere."""
    result = es.smd_from_t(2.1, 20, 20, df=38, design="independent_t", contrast_kind="groups",
                           within_factors=[], outcome_averages_over=[])
    assert result.d == pytest.approx(2.1 * math.sqrt(1 / 20 + 1 / 20), abs=1e-12)
    assert result.route == "t_stat"


def test_an_omnibus_f_over_more_than_two_levels_is_still_refused():
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_f(3.0, 20, 20, a_greater=True, df1=9, df2=342, design="one_way_between",
                      contrast_kind="groups", within_factors=[], outcome_averages_over=[])
    assert "more than two groups" in str(exc.value)


# ------------------------------------------------------------- C5: does it answer the outcome's question
def test_a_main_effect_averaged_over_a_factor_the_outcome_keeps_is_refused_by_name():
    """C5 (i). Heuer's F(1,38) on adaptive shifts is a main effect of age from a 2 x 8 model; the
    outcome asks about the last practice block, not about the mean over eight target directions."""
    ok, reason, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["target direction (8 levels)"], ["block"], 38, 20, 20)
    assert ok is False
    assert "target direction (8 levels)" in reason        # the factor AND its levels are named
    assert "averaged over every level" in reason


def test_an_empty_factor_list_blocks_by_default_when_the_design_is_not_a_two_group_t():
    """C5 (ii) — the fail-open path v1 shipped untested.

    "A 2 x 8 ANOVA" names no factors, so the extractor records `[]`. An empty list is not evidence
    that the model had none.
    """
    ok, reason, _ = es.aggregation_scope_ok("mixed_main_effect", [], [], 38, 20, 20)
    assert ok is False and "were not recorded" in reason
    ok, reason, _ = es.aggregation_scope_ok("one_way_between", [], [], 38, 20, 20)
    assert ok is False and "were not recorded" in reason
    # …and the df alone cannot rescue it: a mixed main effect's error df ARE n_a + n_b - 2
    assert 38 == 20 + 20 - 2


def test_an_empty_factor_list_is_allowed_only_for_a_two_group_t_with_exact_df():
    """C5 (iii)."""
    ok, reason, flags = es.aggregation_scope_ok("independent_t", [], [], 38, 20, 20)
    assert ok is True and reason == "" and flags == []
    # one participant off, and the exactness rule closes it again
    ok, reason, _ = es.aggregation_scope_ok("independent_t", [], [], 37, 20, 20)
    assert ok is False and "were not recorded" in reason
    ok, reason, _ = es.aggregation_scope_ok("independent_t", [], [], None, 20, 20)
    assert ok is False


def test_a_statistic_whose_average_is_the_outcomes_own_window_is_allowed():
    """C5 (iv). The outcome IS "the mean across all eight targets", the model's factors are
    recorded, and the arithmetic is the one the route would apply.

    The conversion itself stays refused for the nine-paper run — `CONVERTIBLE_DESIGNS` is
    unchanged and `mixed_main_effect` is not in it — so this asserts the aggregation gate's answer
    and the arithmetic that would follow it, not an end-to-end conversion.
    """
    ok, reason, flags = es.aggregation_scope_ok(
        "mixed_main_effect", ["target direction (8 levels)"], ["target direction"], 38, 20, 20)
    assert ok is True and reason == "" and flags == ["aggregation_scope_matched"]
    assert es.d_from_f(6.3, 20, 20, 1) == pytest.approx(
        math.sqrt(6.3) * math.sqrt(1 / 20 + 1 / 20), abs=1e-9)
    with pytest.raises(NotConvertible):                  # …and the design gate still refuses it
        es.smd_from_f(6.3, 20, 20, a_greater=True, df1=1, df2=38, design="mixed_main_effect",
                      contrast_kind="groups", within_factors=["target direction (8 levels)"],
                      outcome_averages_over=["target direction"])


def test_one_verbose_outcome_string_does_not_cover_two_within_factors():
    """F4, reproduced from the review: the factor match was a bag-of-words SUBSET test.

    One `outcome_averages_over` entry that mentions both factors covered both of Heuer's within
    factors, so the F(1,38) averaged over eight targets — the statistic C5 exists to refuse,
    worth 0.13-0.17 on Heuer d1 late — passed the scope gate. A match is EQUALITY of the
    normalised factor name, not containment.
    """
    ok, reason, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["block (5 levels)", "target direction (8 levels)"],
        ["the eight target directions in the last block"], 38, 20, 20)
    assert ok is False
    assert "block (5 levels)" in reason and "target direction (8 levels)" in reason


def test_an_outcome_that_keeps_one_level_of_a_factor_does_not_average_over_it():
    """The prompt asks the extractor to qualify a factor in parentheses, and the matcher drops the
    parenthetical — so "block (last block only)" matched "block (5 levels)" exactly. Keeping ONE
    level is the opposite of averaging over the factor, and a level selector never matches."""
    ok, reason, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["block (5 levels)"], ["block (last block only)"], 38, 20, 20)
    assert ok is False and "block (5 levels)" in reason
    ok, _, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["block (5 levels)"], ["the last block"], 38, 20, 20)
    assert ok is False
    ok, _, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["block (5 levels)"], ["block 5"], 38, 20, 20)
    assert ok is False
    # the same factor named plainly, or with its own level count, still matches
    for averaged in (["block"], ["blocks"], ["block (5 levels)"]):
        ok, reason, flags = es.aggregation_scope_ok(
            "mixed_main_effect", ["block (5 levels)"], averaged, 38, 20, 20)
        assert ok is True and flags == ["aggregation_scope_matched"], averaged


def test_a_statistic_kept_at_one_level_of_its_factor_is_refused_end_to_end():
    """The review's end-to-end reproduction: t = 2.1 on 12/12 converted to d = 0.8573 because
    "the last block" contains the word "block"."""
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_t(2.1, 12, 12, df=22, design="independent_t", contrast_kind="groups",
                      within_factors=["block (5 levels)"],
                      outcome_averages_over=["the last block"])
    assert "block (5 levels)" in str(exc.value)


def test_a_named_factor_the_outcome_does_not_name_at_all_is_still_refused():
    """A protocol that writes the factor with different words does not open the route: equality
    is fail-closed, and the prompt tells the extractor to reuse the same names."""
    ok, _, _ = es.aggregation_scope_ok(
        "mixed_main_effect", ["target direction (8 levels)"], ["targets"], 38, 20, 20)
    assert ok is False


# ------------------------------------------------------- P-B: a printed effect size has a contrast too
def test_a_printed_effect_size_that_contrasted_a_constant_is_refused_in_code():
    """F5: `smd_from_reported` had no gate at all, so "d = 1.30 against zero" pooled as the
    between-group effect. The rule is the same one every other route applies."""
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_reported(1.30, 12, 12, positive_means_a_greater=True,
                             contrast_kind="against_constant")
    assert "constant" in str(exc.value)
    with pytest.raises(NotConvertible) as exc:
        es.smd_from_reported(1.30, 12, 12, positive_means_a_greater=True, contrast_kind="unknown")
    assert "nobody recorded" in str(exc.value)
    result = es.smd_from_reported(1.30, 12, 12, positive_means_a_greater=True,
                                  contrast_kind="groups")
    assert result.d == pytest.approx(1.30, abs=1e-12) and result.route == "reported_d"


def test_the_plain_arithmetic_helpers_are_not_forced_to_record_an_estimand():
    """`within_factors=None` means "this call site knows nothing about a model" — the numeric
    helpers called with numbers. The pipeline always passes a list, and `[]` is a refusal."""
    ok, _, _ = es.aggregation_scope_ok("one_way_between", None, None, 22, 12, 12)
    assert ok is True
    assert es.smd_from_t(5.25, 12, 12, df=22, design="independent_t").route == "t_stat"
    # …and the same convention on the printed-effect-size helper: no record, no check
    assert es.smd_from_reported(1.30, 12, 12).route == "reported_d"


def test_the_refusal_for_a_mixed_main_effect_names_aggregation_scope_not_a_different_error_term():
    """P-B: the old reason was false — the between-subjects portion of a split-plot IS the one-way
    ANOVA on subject means, so F_between(1, N-2) = t^2."""
    ok, reason, _ = es.convertibility("mixed_main_effect", 22, 12, 12, contrast_kind="groups")
    assert ok is False
    assert "averaged over every level" in reason
    assert "error term" not in reason
