"""Amendment C: the conversions and gates Task 9 needs, checked against R where R can check them.

Two kinds of reference:

* `validation/fixtures/r_reference.json`, regenerated by `make_r_fixtures.R` — for
  `combine_groups` it holds a raw sample split in two, so the combined summary MUST reproduce the
  whole sample's mean and SD exactly; for the five-number estimators it holds samples whose true
  mean and SD are known; `leave1out` and `regtest(predictor="sqrtninv")` come straight from metafor.
* published formulas (Luo 2018, Shi 2020, Wan 2014, Cochrane 6.5.2.10 / 16.5.4) for the shapes R
  has no function for.

The gates are not statistics but refusals: a statistic from a design that cannot carry a
between-group contrast must raise, not return a plausible number.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest
from scipy.stats import norm

from canopy.stats import conversions as cv
from canopy.stats import effect_sizes as es
from canopy.stats.effect_sizes import NotConvertible
from canopy.stats.meta import egger_test, funnel_data, leave_one_out

FIX = json.loads((Path(__file__).parent.parent / "validation/fixtures/r_reference.json").read_text())


# --------------------------------------------------------------------------- combining arms
def test_combining_two_arms_reproduces_the_whole_sample():
    """Cochrane 6.5.2.10: the point of the formula is that it is exact, so R's raw sample is the
    reference, not another implementation of the same algebra."""
    r = FIX["combine_raw"]
    mean, sd, n = cv.combine_groups(r["m1"], r["sd1"], r["n1"], r["m2"], r["sd2"], r["n2"])
    assert n == r["n"]
    assert mean == pytest.approx(r["mean"], abs=1e-10)
    assert sd == pytest.approx(r["sd"], abs=1e-10)


def test_a_combined_arm_feeds_escalc_unchanged():
    r = FIX["combine_raw"]
    mean, sd, n = cv.combine_groups(r["m1"], r["sd1"], r["n1"], r["m2"], r["sd2"], r["n2"])
    ctrl = r["control"]
    d = es.cohens_d(mean, sd, n, ctrl["m"], ctrl["sd"], ctrl["n"])
    assert d == pytest.approx(r["escalc_d_yi"], abs=1e-9)
    assert es.var_smd(d, n, ctrl["n"], "borenstein") == pytest.approx(r["escalc_d_vi"], abs=1e-9)


def test_combining_identical_arms_keeps_the_mean_and_widens_the_denominator():
    """Two identical arms have no between-arm spread, so the combined SD is just the two sums of
    squares over N−1 = 39 rather than over the 38 degrees of freedom a pooled SD would use."""
    mean, sd, n = cv.combine_groups(10.0, 2.0, 20, 10.0, 2.0, 20)
    assert (mean, n) == (10.0, 40)
    assert sd == pytest.approx(math.sqrt(2 * 19 * 4 / 39))
    assert sd < 2.0


def test_combining_needs_two_real_groups():
    with pytest.raises(ValueError):
        cv.combine_groups(10.0, 2.0, 1, 10.0, 2.0, 0)


# --------------------------------------------------------------------------- shared controls
def test_a_shared_control_is_split_between_the_comparisons():
    """Cochrane 16.5.4: a control arm used in k comparisons contributes n/k to each."""
    assert cv.split_control(30, 3) == pytest.approx(10.0)
    assert cv.split_control(30, 1) == pytest.approx(30.0)


def test_splitting_a_control_needs_at_least_one_comparison():
    with pytest.raises(ValueError):
        cv.split_control(30, 0)


# --------------------------------------------------------------------------- summary statistics
def test_median_and_quartiles_recover_a_known_mean_and_sd():
    r = FIX["five_number"]
    mean, sd = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    assert mean == pytest.approx(r["mean"], rel=0.01)
    assert sd == pytest.approx(r["sd"], rel=0.05)


def test_the_five_number_summary_beats_the_quartiles_alone():
    r = FIX["five_number"]
    _, sd_iqr = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    mean5, sd5 = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                             r["n"])
    assert mean5 == pytest.approx(r["mean"], rel=0.01)
    assert abs(sd5 - r["sd"]) <= abs(sd_iqr - r["sd"]) + 1e-9


def test_the_estimators_still_work_on_a_small_sample():
    r = FIX["five_number_small"]
    mean, sd = cv.mean_sd_from_median_iqr(r["median"], r["q1"], r["q3"], r["n"])
    assert mean == pytest.approx(r["mean"], rel=0.10)
    assert sd == pytest.approx(r["sd"], rel=0.35)


def test_the_wan_fallback_is_available_and_differs_from_shi():
    r = FIX["five_number"]
    _, shi = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                         r["n"])
    _, wan = cv.mean_sd_from_five_number(r["min"], r["q1"], r["median"], r["q3"], r["max"],
                                         r["n"], method="wan")
    assert wan != pytest.approx(shi, abs=1e-12)
    # Wan 2014 eq. 10 is the unweighted average of the two Shi components
    xi = 2 * norm.ppf((r["n"] - 0.375) / (r["n"] + 0.25))
    eta = 2 * norm.ppf((0.75 * r["n"] - 0.125) / (r["n"] + 0.25))
    assert wan == pytest.approx(0.5 * (r["max"] - r["min"]) / xi
                                + 0.5 * (r["q3"] - r["q1"]) / eta, abs=1e-9)


def test_the_quartiles_must_be_ordered():
    with pytest.raises(ValueError):
        cv.mean_sd_from_median_iqr(10.0, 12.0, 8.0, 20)
    with pytest.raises(ValueError):
        cv.mean_sd_from_five_number(5.0, 8.0, 10.0, 9.0, 20.0, 20)


# --------------------------------------------------------------------------- the amendment-C gates
def test_a_two_group_t_converts():
    r = es.smd_from_t(5.25, 12, 12, df=22, design="independent_t", higher_is_better=True)
    assert r.route == "t_stat"
    assert r.d == pytest.approx(es.d_from_t(5.25, 12, 12))
    assert r.details["flags"] == []


@pytest.mark.parametrize("design", ["mixed_main_effect", "interaction", "paired", "ancova",
                                    "welch", "unknown"])
def test_a_design_that_cannot_carry_the_contrast_is_refused(design):
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_t(5.25, 12, 12, df=22, design=design)
    assert design in str(excinfo.value)


def test_degrees_of_freedom_that_do_not_match_the_group_sizes_are_refused():
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_t(5.25, 12, 12, df=40, design="independent_t")
    assert "40" in str(excinfo.value) and "22" in str(excinfo.value)


def test_degrees_of_freedom_within_two_of_the_group_sizes_are_accepted():
    r = es.smd_from_t(5.25, 12, 12, df=20, design="independent_t")
    assert "df_off_by" in r.details["flags"][0]


def test_missing_degrees_of_freedom_are_allowed_but_flagged():
    r = es.smd_from_t(5.25, 12, 12, design="independent_t")
    assert r.details["flags"] == ["df_missing"]


def test_an_f_with_more_than_one_numerator_degree_of_freedom_is_refused():
    with pytest.raises(NotConvertible) as excinfo:
        es.smd_from_f(7.58, 12, 12, df1=3, df2=22, design="one_way_between", a_greater=True)
    assert "df1" in str(excinfo.value)


def test_a_one_way_between_f_converts():
    r = es.smd_from_f(7.58, 12, 12, df1=1, df2=22, design="one_way_between", a_greater=True)
    assert r.d == pytest.approx(es.d_from_f(7.58, 12, 12, 1))
    assert r.route == "f_stat"


def test_the_mixed_design_f_that_bock_prints_is_refused():
    """F(1,22)=7.58 for the grouping factor in a mixed ANOVA: right dfs, wrong error term."""
    with pytest.raises(NotConvertible):
        es.smd_from_f(7.58, 12, 12, df1=1, df2=22, design="mixed_main_effect", a_greater=True)


def test_a_p_value_is_gated_the_same_way():
    with pytest.raises(NotConvertible):
        es.smd_from_p(0.03, 12, 12, design="interaction", a_greater=True)
    r = es.smd_from_p(0.03, 12, 12, df=22, design="independent_t", a_greater=True)
    assert r.route == "p_value"


def test_convertibility_explains_itself():
    ok, reason, flags = es.convertibility("independent_t", 22, 12, 12)
    assert ok is True and reason == "" and flags == []
    ok, reason, flags = es.convertibility("paired", 22, 12, 12)
    assert ok is False and "paired" in reason


# --------------------------------------------------------------------------- funnel / Egger / LOO
def test_egger_without_group_sizes_keeps_the_classic_predictor():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    assert result.predictor == "precision" and result.k == late["k"]
    assert result.df == late["k"] - 2


def test_egger_matches_the_rmd_regression():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    ref = late["egger_rmd"]
    assert result.intercept == pytest.approx(ref["intercept"], abs=1e-6)
    assert result.intercept_se == pytest.approx(ref["intercept_se"], abs=1e-6)
    assert result.t == pytest.approx(ref["intercept_t"], abs=1e-6)
    assert result.p == pytest.approx(ref["intercept_p"], abs=1e-6)


def test_the_pustejovsky_rodgers_predictor_matches_metafor_regtest():
    """With group sizes the predictor is √((nA+nB)/(nA·nB)), which does not depend on the effect
    size itself — metafor::regtest(predictor="sqrtninv") with ni = nA·nB/(nA+nB)."""
    ref = FIX["egger_pr"]
    result = egger_test(ref["TE"], ref["seTE"], n_a=ref["n_a"], n_b=ref["n_b"])
    assert result.predictor == "sqrt_inv_n"
    assert result.t == pytest.approx(ref["zval"], abs=1e-8)
    assert result.p == pytest.approx(ref["pval"], abs=1e-8)
    assert result.estimate == pytest.approx(ref["est"], abs=1e-8)
    assert result.estimate_ci_low == pytest.approx(ref["ci.lb"], abs=1e-8)
    assert result.estimate_ci_high == pytest.approx(ref["ci.ub"], abs=1e-8)
    assert result.df == ref["dfs"]


def test_the_asymmetry_coefficient_has_one_unambiguous_name():
    """`intercept` is the asymmetry coefficient in BOTH variants (the fitted intercept for the
    classic predictor, the fitted slope for the sample-size one), so downstream code reads one
    field; the aliases say which is which."""
    ref = FIX["egger_pr"]
    classic = egger_test(FIX["cisneros_late"]["TE"], FIX["cisneros_late"]["seTE"])
    modified = egger_test(ref["TE"], ref["seTE"], n_a=ref["n_a"], n_b=ref["n_b"])
    for result in (classic, modified):
        assert result.bias_coefficient == result.intercept
        assert result.limit_estimate == result.estimate == result.slope
        assert result.t == pytest.approx(result.intercept / result.intercept_se, abs=1e-12)


def test_egger_needs_three_studies():
    """metafor::regtest refuses below k=3, and so must we: two studies leave no residual degrees
    of freedom to test the asymmetry coefficient against."""
    with pytest.raises(ValueError, match="3 studies"):
        egger_test([0.1, 0.2], [0.1, 0.2])


def test_the_classic_egger_also_matches_metafors_lm_variant():
    late = FIX["cisneros_late"]
    result = egger_test(late["TE"], late["seTE"])
    assert result.t == pytest.approx(FIX["egger_sei_lm"]["zval"], abs=1e-8)
    assert result.p == pytest.approx(FIX["egger_sei_lm"]["pval"], abs=1e-8)


def test_leave_one_out_matches_metafor():
    late = FIX["cisneros_late"]
    ref = FIX["leave_one_out"]
    vi = np.asarray(late["seTE"], float) ** 2
    rows = leave_one_out(late["TE"], vi, method="REML")
    assert len(rows) == ref["k"]
    assert [r.omitted for r in rows] == list(range(ref["k"]))
    np.testing.assert_allclose([r.estimate for r in rows], ref["estimate"], atol=1e-6)
    np.testing.assert_allclose([r.se for r in rows], ref["se"], atol=1e-6)
    np.testing.assert_allclose([r.ci_low for r in rows], ref["ci.lb"], atol=1e-5)
    np.testing.assert_allclose([r.ci_high for r in rows], ref["ci.ub"], atol=1e-5)
    np.testing.assert_allclose([r.tau2 for r in rows], ref["tau2"], atol=1e-5)
    np.testing.assert_allclose([100 * r.I2 for r in rows], ref["I2"], atol=1e-4)


def test_leave_one_out_carries_the_study_labels():
    rows = leave_one_out([0.1, 0.2, 0.3], [0.01, 0.02, 0.03], labels=["a", "b", "c"])
    assert [r.label for r in rows] == ["a", "b", "c"] and rows[0].k == 2


def test_funnel_data_gives_the_points_and_the_pseudo_confidence_contours():
    late = FIX["cisneros_late"]
    vi = np.asarray(late["seTE"], float) ** 2
    data = funnel_data(late["TE"], vi, labels=late["study"])
    assert len(data["yi"]) == len(late["TE"]) and len(data["sei"]) == len(late["TE"])
    assert data["estimate"] == pytest.approx(late["REML"]["TE.random"], abs=1e-6)
    assert data["se_max"] == pytest.approx(max(late["seTE"]))
    for level in (0.95, 0.99):
        contour = data["contours"][str(level)]
        assert contour["se"][0] == 0.0
        assert contour["low"][0] == pytest.approx(data["estimate"])
        assert contour["low"][-1] < data["estimate"] < contour["high"][-1]
    assert data["labels"][0] == late["study"][0]


# --------------------------------------------------------------------------- digitisation variance
def test_finite_differences_reproduce_the_analytic_partial_derivatives():
    """d = (m_a − m_b)/s_p, so ∂d/∂m_a = 1/s_p exactly — the numerical version must agree."""
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)

    def d_of(m_a, sd_a, m_b, sd_b):
        return es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12)

    var, parts = cv.partial_variance(d_of, values, {"m_a": 0.5, "m_b": 0.5})
    sp = es.pooled_sd(11.12, 12, 11.82, 12)
    analytic = (0.5 / sp) ** 2 + (0.5 / sp) ** 2
    assert var == pytest.approx(analytic, rel=1e-6)
    assert parts["m_a"] == pytest.approx((0.5 / sp) ** 2, rel=1e-6)
    assert "sd_a" not in parts


def test_an_input_with_no_uncertainty_contributes_nothing():
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)
    var, parts = cv.partial_variance(
        lambda m_a, sd_a, m_b, sd_b: es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12), values,
        {"m_a": 0.5, "m_b": None, "sd_a": 0.0})
    assert set(parts) == {"m_a"} and var > 0


def test_no_uncertainty_at_all_is_zero_variance():
    var, parts = cv.partial_variance(lambda x: x ** 2, {"x": 3.0}, {})
    assert var == 0.0 and parts == {}


def test_the_dispersion_partials_are_included_when_the_digitizer_measured_them():
    values = dict(m_a=31.51, sd_a=11.12, m_b=12.28, sd_b=11.82)
    var, parts = cv.partial_variance(
        lambda m_a, sd_a, m_b, sd_b: es.cohens_d(m_a, sd_a, 12, m_b, sd_b, 12), values,
        {"m_a": 0.5, "m_b": 0.5, "sd_a": 0.4, "sd_b": 0.4})
    assert set(parts) == {"m_a", "m_b", "sd_a", "sd_b"}
    assert var > math.fsum(parts[k] for k in ("m_a", "m_b")) > 0
