suppressPackageStartupMessages({library(meta); library(metafor)})
options(digits=10)
# Worked example: 5 studies, group A = young (reference), group B = older; positive d = older higher
dat <- data.frame(study=paste0("S",1:5),
  m1=c(10.0, 12.5,  8.0, 15.0, 11.0), sd1=c(2.0, 3.0, 2.5, 4.0, 3.5), n1=c(12, 20, 15, 30, 10),   # young
  m2=c(11.2, 11.0,  9.5, 17.0, 13.0), sd2=c(2.5, 3.2, 2.0, 4.5, 3.0), n2=c(12, 18, 15, 25, 10))   # older
sp <- with(dat, sqrt(((n1-1)*sd1^2 + (n2-1)*sd2^2)/(n1+n2-2)))
d  <- with(dat, (m2-m1)/sp)
sed <- with(dat, sqrt((n1+n2)/(n1*n2) + d^2/(2*(n1+n2-2))))
cat("d:", d, "\nSE(d):", sed, "\n")
# metafor escalc variants
es <- escalc(measure="SMD", m1i=m2, sd1i=sd2, n1i=n2, m2i=m1, sd2i=sd1, n2i=n1, data=dat)
cat("g (metafor):", es$yi, "\nvi LS (metafor):", es$vi, "\n")
es2 <- escalc(measure="SMD", m1i=m2, sd1i=sd2, n1i=n2, m2i=m1, sd2i=sd1, n2i=n1, data=dat, vtype="UB")
cat("vi UB:", es2$vi, "\n")
mc <- metacont(n2, m2, sd2, n1, m1, sd1, data=dat, sm="SMD")
cat("g (meta metacont exact):", mc$TE, "\nseTE:", mc$seTE, "\n")

for (meth in c("REML","DL","PM")) {
 mg <- metagen(TE=d, seTE=sed, studlab=dat$study, sm="SMD", random=TRUE, common=FALSE, method.tau=meth, method.random.ci="classic", prediction=TRUE, method.predict="HTS")
 cat("\n=== meta::metagen method.tau=", meth, " ===\n")
 cat("TE.random", mg$TE.random, "seTE.random", mg$seTE.random, "z", mg$statistic.random, "p", mg$pval.random, "\n")
 cat("CI", mg$lower.random, mg$upper.random, "\n")
 cat("tau2", mg$tau2, "tau", mg$tau, "tau2 CI", mg$lower.tau2, mg$upper.tau2, "\n")
 cat("Q", mg$Q, "df", mg$df.Q, "pQ", mg$pval.Q, "I2", mg$I2, "H", mg$H, "\n")
 cat("PI (HTS, k-2 df)", mg$lower.predict, mg$upper.predict, " seTE.predict", mg$seTE.predict, "\n")
 mgV <- update(mg, method.predict="V")
 cat("PI (V, k-1 df, meta>=8 default)", mgV$lower.predict, mgV$upper.predict, "\n")
 mgS <- update(mg, method.predict="S")
 cat("PI (S, z)", mgS$lower.predict, mgS$upper.predict, "\n")
 mgHK <- update(mg, method.random.ci="HK")
 cat("HK: TE", mgHK$TE.random, "se", mgHK$seTE.random, "t", mgHK$statistic.random, "df", mgHK$df.random, "p", mgHK$pval.random, "CI", mgHK$lower.random, mgHK$upper.random, "\n")
 mgHKse <- update(mg, method.random.ci="HK", adhoc.hakn.ci="se")
 cat("HK adhoc se: se", mgHKse$seTE.random, "CI", mgHKse$lower.random, mgHKse$upper.random, "\n")
 cat("weights.random", mg$w.random/sum(mg$w.random), "\n")
}
cat("\n=== metafor rma REML ===\n")
r <- rma(yi=d, vi=sed^2, method="REML")
print(r, digits=8)
cat("tau2", r$tau2, "se.tau2", r$se.tau2, "I2", r$I2, "H2", r$H2, "QE", r$QE, "QEp", r$QEp, "\n")
print(confint(r, digits=8))
print(predict(r, digits=8))
print(predict(r, pi.type="Riley", digits=8))
rk <- rma(yi=d, vi=sed^2, method="REML", test="knha")
print(rk, digits=8); print(predict(rk, digits=8))
cat("REML ll", logLik(r), "\n")
r_v <- rma(yi=d, vi=sed^2, method="REML", verbose=TRUE)
cat("\n=== Egger (Rmd style lm) ===\n")
eg <- lm(I(d/sed) ~ I(1/sed))
print(summary(eg)$coefficients)
mg <- metagen(TE=d, seTE=sed, studlab=dat$study, sm="SMD", random=TRUE, common=FALSE, method.tau="REML")
print(metabias(mg, method.bias="Egger", k.min=3))
print(regtest(r, model="lm"))
cat("\n=== trimfill ===\n")
tf <- trimfill(r); print(tf, digits=6)
tfm <- trimfill(mg); cat("meta trimfill k0", tfm$k0, "TE", tfm$TE.random, "CI", tfm$lower.random, tfm$upper.random, "\n")
cat("\n=== selmodel (Vevea-Hedges step) ===\n")
sm <- try(selmodel(r, type="stepfun", steps=c(0.025,1)), silent=TRUE); if(!inherits(sm,"try-error")) print(sm)
cat("\n=== 2-study edge & zero-tau2 case ===\n")
r2 <- rma(yi=c(0.2,0.25,0.22,0.18), vi=c(0.04,0.05,0.03,0.045), method="REML"); print(r2, digits=6); print(predict(r2))
mg2 <- metagen(TE=c(0.2,0.25,0.22,0.18), seTE=sqrt(c(0.04,0.05,0.03,0.045)), sm="SMD", random=TRUE, common=FALSE, method.tau="REML", prediction=TRUE, method.predict="HTS")
cat("meta zero-tau: TE", mg2$TE.random, "CI", mg2$lower.random, mg2$upper.random, "PI", mg2$lower.predict, mg2$upper.predict, "tau2", mg2$tau2, "I2", mg2$I2, "\n")
